Update issue templates
Deci-AI/super-gradients pull request #121
Opened 2022-01-27 15:39 UTC by jonathan-sha

2022-01-30 09:00 UTC, shaydeci submitted a review, later dismissed
lgtm

2022-01-30 09:47 UTC, jonathan-sha commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Relevant HW info, GPU [e.g. nvidia-smi]
Add cuda version

2022-01-30 10:58 UTC, RanZilberstein commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
I would like to see information about the python libraries installed - like running pip [freeze](https://pip.pypa.io/en/stable/cli/pip_freeze/) command. This way we can reproduce the bug in exact environment.

2022-01-30 11:04 UTC, RanZilberstein requested changes
Added a small comment to fix + Please look at the .md view format, you might want to add new lines and change the appearance a bit.

2022-01-30 13:29 UTC, RanZilberstein approved these changes
lgtm

2022-01-31 13:33 UTC, avideci commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Relevant HW info, GPU [e.g. nvidia-smi]
I think nvidia-smi has cuda version

2022-02-01 08:53 UTC, shaydeci approved these changes

2022-02-01 08:54 UTC, merged