Feature/sg optional progressbar prediction
Deci-AI/super-gradients pull request #1465
Opened 2023-09-14 11:24 UTC by EduardoPach

What does this PR do:

Adds functionality mentioned in https://github.com/Deci-AI/super-gradients/issues/1329

2023-09-19 03:12 UTC, EduardoPach commented
@Louis-Dupont can you review it?

2023-09-21 13:08 UTC, BloodAxe commented on src/super_gradients/training/models/detection_models/yolo_base.py
> +        :param show_progress_bar: If True, show a progress bar.
Please ensure indentation is preserved:
```
        :param batch_size:        Maximum number of images to process at the same time.
        :param fuse_model:        If True, create a copy of the model, and fuse some of its layers to increase performance. This increases memory usage.
        :param show_progress_bar: If True, show a progress bar.
```

2023-09-21 13:09 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +        self, inputs: Union[str, ImageSource, List[ImageSource]], batch_size: Optional[int] = 32, show_progress_bar: Optional[bool] = True
No need for Optional[] here.

2023-09-21 13:09 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +            return self.predict_video(inputs, batch_size, show_progress_bar)
Please use explicit arguments here `show_progress_bar=show_progress_bar` and elsewhere

2023-09-21 13:11 UTC, BloodAxe commented
Thanks for your PR. Unfortunately it look like it contains **unsigned** commits with is a hard requirement. Please check https://github.com/Deci-AI/super-gradients/blob/master/CONTRIBUTING.md for information on setting up the signed commits.

2023-09-21 15:41 UTC, BloodAxe commented
No. What you need to do is create another branch starting from master, then move your commits from PR branch to the 
new branch and force push it to the remote under the old name. Let's say your PR branch named 'feature/my_awesome_pr'
then you need to do the following:

```bash
git checkout master
git checkout -b feature/my_awesome_pr_signed
git merge --squash --no-commit feature/my_awesome_pr
git commit -S -m "My signed commit"
git push -f origin feature/my_awesome_pr_signed:feature/my_awesome_pr
```

Last command will overwrite your PR branch with the new signed commit containing all changes from the PR. 

LMK if this snippet would work (written from memory). If yes, we will update contribution guide to contain this text to help other contributors (Btw, if it works feel free to make a second PR with these instructions).

2023-09-22 21:22 UTC, EduardoPach commented
> No. What you need to do is create another branch starting from master, then move your commits from PR branch to the new branch and force push it to the remote under the old name. Let's say your PR branch named 'feature/my_awesome_pr' then you need to do the following:
> 
> ```shell
> git checkout master
> git checkout -b feature/my_awesome_pr_signed
> git merge --squash --no-commit feature/my_awesome_pr
> git commit -S -m "My signed commit"
> git push -f origin feature/my_awesome_pr_signed:feature/my_awesome_pr
> ```
> 
> Last command will overwrite your PR branch with the new signed commit containing all changes from the PR.
> 
> LMK if this snippet would work (written from memory). If yes, we will update contribution guide to contain this text to help other contributors (Btw, if it works feel free to make a second PR with these instructions).

It seemed to work! I'll update the `CONTRIBUTING.md` shortly

2023-09-23 05:38 UTC, BloodAxe commented
Glad it helped. Regarding PR to contributing md - probably no need, there is already one made by me https://github.com/Deci-AI/super-gradients/pull/1486 :)

2023-09-27 06:20 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +        if (n_images is not None and n_images == 1) or not show_progress_bar:
So here you've introduced a bug in my opinion.
By adding `or not show_progress_bar:` to the condition `if (n_images is not None and n_images == 1)` you are forcing code to go `images_predictions = [next(iter(images_predictions))]` path if progress bar is disabled.
But this path would process only one element of the sequence, not all of them.
What you should be doing instead is this:
`images_predictions = [image_predictions for image_predictions in tqdm(images_predictions, total=n_images, desc="Predicting Images", disable=not show_progress_bar)]`

Btw it is a good idea to add a test to `tests/unit_tests/test_predict.py` which would take any detection model and run predict on few images with show_progress_bar=False and ensure than number of predictions matches number of input images.

2023-10-03 08:57 UTC, BloodAxe requested changes
https://github.com/Deci-AI/super-gradients/pull/1465#discussion_r1338094118

2023-10-03 13:46 UTC, EduardoPach commented
> [#1465 (comment)](https://github.com/Deci-AI/super-gradients/pull/1465#discussion_r1338094118)

Sorry for the delay, gonna fix this right now

2023-10-05 11:33 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +            images_predictions = [image_predictions for image_predictions in tqdm(images_predictions, total=n_images, desc="Predicting Video")]
Here `disable=not show_progress_bar` is missing

2023-10-05 11:35 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +        if not show_progress_bar:
And this check does not make sense to me. Why are you changing logic of original implementation?

2023-10-05 11:35 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +        if not show_progress_bar:
Same here. Do not add IFs where they were not present.

2023-10-05 11:35 UTC, BloodAxe commented on src/super_gradients/training/pipelines/pipelines.py
> +            images_predictions = [image_predictions for image_predictions in tqdm(images_predictions, total=n_images, desc="Predicting Video")]
`disable` is missing

2023-10-05 11:36 UTC, BloodAxe commented
@EduardoPach there is still some leftovers remaining. I left some comments for you to address.

2023-10-06 16:41 UTC, EduardoPach commented
@BloodAxe Now I believe should be done!

2023-10-11 06:43 UTC, BloodAxe approved these changes
LGTM

2023-10-11 12:40 UTC, BloodAxe commented
@EduardoPach I think we are ready to merge your PR, however i still see some non-signed commits present in this PR, like this [one](https://github.com/Deci-AI/super-gradients/pull/1465/commits/6d61443f3d3b20bef16aa7fc26315640f6d7e534).
Can you please fix this and we can finally merge it )

2023-10-18 00:53 UTC, EduardoPach commented
> @EduardoPach I think we are ready to merge your PR, however i still see some non-signed commits present in this PR, like this [one](https://github.com/Deci-AI/super-gradients/pull/1465/commits/6d61443f3d3b20bef16aa7fc26315640f6d7e534). Can you please fix this and we can finally merge it )

Fixed!

2024-01-08 10:27 UTC, BloodAxe commented
Closing as stale

2024-01-08 10:27 UTC, closed without merging