Adding a notebook with upload to the Deci Lab - wip [ci skip]
Deci-AI/super-gradients pull request #151
Opened 2022-03-17 22:13 UTC by daniel-deci

2022-03-18 11:04 UTC, daniel-deci commented on src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
> +if __name__ == '__main__':
I added this as a commodity for make it easy to debug from PyCharm

2022-03-18 11:17 UTC, daniel-deci commented
@shaydeci @lotem-deci 
This can be reviewed but can't be merged until we publish the [deci-lab-client](https://github.com/Deci-AI/deci-lab-client/pull/21)

2022-03-21 07:46 UTC, shaydeci commented on src/super_gradients/training/utils/callbacks.py
> -            model.load_state_dict(model_state_dict_path)
This line shouldn't be removed.  There's a a reason we load the weights from model_state_dict_path-
The callback is fired at the end of training and the weights at that point might not be optimal (or just not the ones we meant when specifying them in ckpt_name.

2022-04-04 07:34 UTC, shaydeci requested changes
See inline comments.
We need to check this works for at least most of the architectures, and definitely the ones the require prep_model_for_conversion prior to the call.
Make sure when these architectures are built, that the call actually does some manipulation (by passing the right arguments through arch params when building them, for instance take a look at repvgg prep_model_for_conversion)

2022-04-04 07:34 UTC, shaydeci commented on src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
>  model.build_model(net)
We need to make sure conversion works for our SG supported architectures (for example calling model.build_model("yolo_v5n")).
We need to at least do this for some architecture families in each task. You can take the code from our Quickstart notebooks for the different tasks and modify the number of epochs to something small, and add the deci lab upload callback to the phase callbacks as done here.

2022-04-04 07:34 UTC, shaydeci commented on src/super_gradients/training/utils/callbacks.py
> +        self.platform_client.add_model(
For some architectures we must call prep_model_for_conversion().
Please check if we need to do so before passing the model through local_loaded_model arg by:
model = model.module.cpu()
if hasattr(model, "prep_model_for_conversion"):
    model.prep_model_for_conversion(input_size=self.model_met_data.input_dimensions)

(not sure this is how to get the input dimensions from ModelMetaData but you get the principle...)

2022-05-29 13:19 UTC, shaydeci approved these changes
LGTM

2022-05-30 10:10 UTC, lotem-deci approved these changes
LGTM

2022-05-30 10:55 UTC, merged