Fix ExtremeBatchDetectionVisualizationCallback when multiscale collate fn in use
Deci-AI/super-gradients pull request #1697
Opened 2023-12-11 15:09 UTC by BloodAxe

Fixes a bug that occurs when using ExtremeBatchDetectionVisualizationCallback and using DDP and multiscale collate fn.
Also fixes an issue of wrong epoch being logged which prevented images to being displayed in WandB

2023-12-11 20:55 UTC, Louis-Dupont submitted a review, later dismissed
LGTM

2023-12-12 08:22 UTC, shaydeci requested changes

2023-12-12 11:44 UTC, shaydeci submitted a review, later dismissed
LGTM

2023-12-18 09:02 UTC, shaydeci approved these changes
LGTM

2023-12-18 09:32 UTC, merged