Feature/sg 36 yolox model
Deci-AI/super-gradients pull request #189
Opened 2022-04-27 14:13 UTC by yurkovak

Changes:
* Split yolov5.py into yolov5_base.py and yolov5.py
* Allow overriding stem type with arch_params['stem_type'], by default it's defined by yolo_type and yolo_version
* Add yolox yamls

The tremendous number of involved files and changes is due to:
* Some imports from yolov5 that now have to be yolov5_base;
* The renaming of a file is unfortunately displayed as a brand new file

2022-04-27 15:24 UTC, yurkovak commented
For the reference, continues changes from #136

2022-05-01 07:50 UTC, shaydeci requested changes
minor inline comment

2022-05-01 07:50 UTC, shaydeci commented on tests/unit_tests/yolox_unit_test.py
> +                assert yolo_model._head.anchors.num_anchors == 0
why not add it the test suite runner ?

2022-05-03 08:12 UTC, shaydeci commented on tests/unit_tests/yolox_unit_test.py
> +                assert yolo_model._head.anchors.num_anchors == 0
Added it for you.

2022-05-03 08:41 UTC, shaydeci approved these changes
lgtm

2022-05-03 08:41 UTC, merged