Added import of quantized modules so they get registered
Deci-AI/super-gradients pull request #542
Opened 2022-12-05 09:43 UTC by spsancti

2022-12-05 09:47 UTC, shaydeci approved these changes
LGTM

2022-12-05 10:10 UTC, shaydeci requested changes
**Sorry for the approve before.

We need to talk this over, since PyTorch quantization is an optional installation.

2022-12-19 13:32 UTC, ofrimasad reviewed
minor comment

2022-12-19 13:32 UTC, ofrimasad commented on src/super_gradients/modules/__init__.py
> +    logger.warning(f"Failed to import pytorch_quantization: {import_err}")
please change this to debug (not warning)

2022-12-19 14:56 UTC, ofrimasad approved these changes
LGTM

2022-12-19 14:57 UTC, shaydeci approved these changes

2022-12-19 15:08 UTC, merged