Add dataset instruction
Deci-AI/super-gradients pull request #602
Opened 2023-01-08 07:29 UTC by Louis-Dupont

2023-01-08 09:19 UTC, shaydeci requested changes
Adding the structures in the dataset objects docs is nice to have but not what we aimed for.
We should add an additional section in the Readme.md "public datasets setup instructions" followed by the steps the users need to executer in order to start training with them in recipes.

2023-01-15 15:12 UTC, shaydeci requested changes
Please add cityscapes instructions to Dataset_Setup_Instructions then LGTM.

2023-01-15 15:12 UTC, shaydeci commented on src/super_gradients/training/datasets/Dataset_Setup_Instructions.md
> +### Segmentation Datasets
Cityscapes ?

2023-01-16 11:37 UTC, Louis-Dupont commented on src/super_gradients/training/datasets/Dataset_Setup_Instructions.md
> +### Segmentation Datasets
Added 709a1982fad825f5922bc20c72aa5b52b9b8fde1

2023-01-16 15:42 UTC, shaydeci approved these changes
LGTM

2023-01-17 08:39 UTC, merged