Add log readme
Deci-AI/super-gradients pull request #664
Opened 2023-01-29 16:06 UTC by Louis-Dupont

2023-01-29 16:18 UTC, shaydeci requested changes
I feel like this is missing quite a lot of what we are aiming for...

All we do here is flash some parameters to integrate WandB and Clearml, when I think the appropriate thing to do here is to explain about SG loggers, detailing how one can access their methods (phase callbacks).

Also, there's quite a lot to say on what values we log by default, what values we print etc.
Don't forget about Tensorboards too.

I think there's quite a lot to detail about regarding training with configs- there's the .hydra directory, the "recipe_config" which is logged when using train_from_config (and if we are already talking about additional logs- additional_logs that one can pass through train() is not mentioned here either).

2023-01-30 07:05 UTC, ofrimasad reviewed
Please note that the SGLoggers should be on a different document (Monitoring). copy them to another document. 
missing in this file are the different types of logs and what is in each one of them. 
- console_<date>.txt
- log_<date>.txt
- sg_logs_<date>.txt 
Also, how to set a different log level
Crash tips and how to turn them off

2023-01-30 07:05 UTC, ofrimasad commented on documentation/source/Logs.md
> +- When instantiating the super_gradients.Trainer, all console outputs and logs will be redirected to the experiment folder `/<path>/<to>/<experiments>/<experiment_name>/sg_logs_<date>.log`.
I think it is saved in console_<date>.txt

2023-01-31 07:30 UTC, ofrimasad requested changes
Beautiful documentation!
just remove the code that was already pushed in the second PR please.
see my minor comment inline

2023-01-31 07:30 UTC, ofrimasad commented on documentation/source/logs.md
> +**How to set log level?** You can filter the logs displayed on the console by setting `CONSOLE_LOG_LEVEL=<LOG-LEVEL> # DEBUG/INFO/WARNING/ERROR`
maybe states "setting *environment variable* ..."

2023-01-31 08:00 UTC, Louis-Dupont commented on documentation/source/logs.md
> +**How to set log level?** You can filter the logs displayed on the console by setting `CONSOLE_LOG_LEVEL=<LOG-LEVEL> # DEBUG/INFO/WARNING/ERROR`
changed

2023-02-01 13:16 UTC, ofrimasad approved these changes
LGTM

2023-02-01 13:58 UTC, shaydeci approved these changes
LGTM

2023-02-01 13:58 UTC, merged