model zoo
Deci-AI/super-gradients pull request #725
Opened 2023-02-20 13:34 UTC by ofrimasad

2023-02-20 13:39 UTC, BloodAxe commented on documentation/source/model_zoo.md
> +
PPYoloE missing?

2023-03-08 10:03 UTC, shaydeci requested changes

2023-03-08 10:03 UTC, shaydeci commented on documentation/source/model_zoo.md
> +</details>
Also pose estimation

2023-03-12 10:18 UTC, ofrimasad commented on documentation/source/model_zoo.md
> +</details>
added

2023-03-12 10:18 UTC, ofrimasad commented on documentation/source/model_zoo.md
> +
added

2023-03-13 09:58 UTC, BloodAxe approved these changes

2023-03-13 18:44 UTC, Louis-Dupont approved these changes
LGTM

2023-03-14 07:51 UTC, shaydeci approved these changes
LGTM

2023-03-14 07:52 UTC, merged