Tab completion
Deci-AI/super-gradients pull request #850
Opened 2023-04-20 10:12 UTC by BloodAxe

See documentation file in this PR for more details

2023-04-20 10:40 UTC, Louis-Dupont commented
Just follow the instructions and it ran pretty fast on my computer (Mac), but I only see some keys. Is it normal?
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/35190946/233342148-1abbc8aa-3650-42e2-8a02-e5f66f84eb5e.png">

2023-04-20 12:40 UTC, BloodAxe commented
I would say yes, it does not show you "all" keys for a given config. For some reason root settings are not there. Perhaps we should evaluate this feature more thoroughly to see whether it is really helps.

2023-04-24 06:48 UTC, BloodAxe commented
It is. I assume you expected to see all root parameters, right? We have no control on tab completion so if it is not providing useful completion - i guess we can reconsider whether we want to have this feature.

2023-05-01 12:25 UTC, shaydeci requested changes

2023-05-01 12:25 UTC, shaydeci commented on documentation/source/TabCompletion.md
> +* You need to enable tab completion explicitly for each entry point in your application. In other words, if your project.
if your project....
Line swapped here I believe.

2023-05-01 12:25 UTC, shaydeci commented on documentation/source/TabCompletion.md
> +* Tab completion is not supported for running train_from_recipe using `-m` form: `python -m super_gradients.train_from_recipe ...`.
Why not actually?
Cant we just do the same wherever SG package is stored in ? Or is it a problem with the fact that its being ran as a module?

2023-05-07 09:09 UTC, shaydeci commented
Im closing this down, as I dont think we currently benefit enough from tab completion.
Perhaps we can revisit this in the future, when tab completion is more ready from Hydra's side.

2023-05-07 09:09 UTC, closed without merging