added find_detection_score_threshold
Deci-AI/super-gradients pull request #973
Opened 2023-05-10 15:50 UTC by itaylevy-deci

computes the best threshold for each class in an efficient manner without added loops

2023-05-16 08:08 UTC, BloodAxe commented on utils_script/find_detection_score_threshold.py
> +    class_names = COCO_DETECTION_CLASSES_LIST  # change this line to use a different dataset
Great work. I really love the way to find thresholds using command-line args approach: ` python find_detection_score_threshold.py --config-name=coco2017_yolox architecture=yolox_n
            checkpoint_params.pretrained_weights=coco`
However it seems that for other dataset one have to change the hard-coded `class_names` constant. Is it possible to improve this part and move class names to dataset_params maybe?

Also, consider moving this script to `super_gradients.scripts` to enable using this script as follows:
`python -m super_gradients.find_detection_score_threshold --config-name=coco2017_yolox architecture=yolox_n checkpoint_params.pretrained_weights=coco`

2023-05-16 13:55 UTC, shaydeci requested changes
Very nice work!

- See one comment inline.
- There's still a missing piece we spoke of - we get the different thresholds per class, then we wish to use these in our NMS.
- It would also be great to just have the threshold that maximizes F1.
- Nice to have: same mechanism for the other metrics (mAP etc).

2023-05-16 13:55 UTC, shaydeci commented on src/super_gradients/training/utils/detection_utils.py
> +    return ap, precision, recall, best_score_threshold
I think it would be safer to not return the threshold here..
perhaps set it as an attribute, or return it somewhere else.

2023-05-23 14:07 UTC, shaydeci requested changes

2023-05-23 14:07 UTC, shaydeci commented on src/super_gradients/training/metrics/detection_metrics.py
> +    :param calc_best_score_thresholds       Whether to calculate the best score threshold per class
If we leave it this way, please give some guidance what we will have retiurned when we use this flag.

2023-06-11 07:00 UTC, shaydeci commented
@itaylevy-deci This PR has been open for quite a while now and has some comments that were not addressed.

2023-06-28 08:31 UTC, BloodAxe approved these changes
LGTM

2023-06-28 08:35 UTC, shaydeci approved these changes
LGTM

2023-06-29 09:21 UTC, merged